apiVersion: v1
kind: Service
metadata:
  name: sbmvnpodinfo-service
spec:
  type: NodePort
  selector:
    app: sbmvnpodinfo
  ports:
  - protocol: TCP
    nodePort: 30301
    port: 8088
    targetPort: 8088
